### ISSUE TITLE
v2.0.0 RoadMap

### ISSUE THREAD

**Issue by gfranko** [BoilerplateMVC/Backbone-Require-Boilerplate#42]
- [x] Add the latest version of Backbone and remove the Backbone `shim` configurations
- [x] Update to the latest version of AMDClean and update the AMDClean configuration inside of the Gruntfile
- [ ] Finally figure out how to integrate Jasmine tests that can be run with PhantomJS and reuse the same configuration file as the app.  I should take another look at the work @betaselam did to integrate Karma and Istanbul #39 
- [ ] Integrate automated test coverage reporting with Istanbul #39 
- [ ] Integrate live reload support in the Gruntfile.
- [ ] Replace Require.js with [Cajon](https://github.com/requirejs/cajon) so that both CommonJS and AMD modules can be loaded
- [ ] Integrate AMDClean v2.1 (AMDClean v2.1 needs to be released first) and the RequireJS optimizer `cjsTranslate` option to support both CommonJS and AMD modules
- [x] Fix #41 - Make sure the Plato Reports are there 
- [ ] Create a Yeoman Generator that can be used to set up Backbone-Require-Boilerplate. **This will take the most work**
